### PR TITLE
fix: error failed connect

### LINKED ISSUE #5: Failed (undefined) connect ECONNREFUSED 127.0.0.1:443

### PR DESCRIPTION
**Pull request by UncleVic**
closes #5

### CODE REVIEW

**Review by derevnjuk — CHANGES_REQUESTED** [review]
Rebase the branch to exclude redundant commits. Also, rework workflows to run tests only when PR is open

```
# ./github/workflows/test.yml
name: CI / Automated testing

on:
  pull_request:
    branches:
      - '**'

# steps
```

and

```
# ./github/workflows/release.yml
name: Release

on:
  push:
    branches:
      - master

# steps
```

**Review by derevnjuk — CHANGES_REQUESTED** [review]
Please the branch onto master since your PR contains stale changes

**Comment by UncleVic** [comment]
done

**Review by derevnjuk — APPROVED** [review]
LGTM 👍🏾

**Pull request merged**
